version: '2.3'
services:
  db:
    image: informaticsmatters/rdkit_cartridge
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    ports:
      - '5432:5432'
  main:
    build: .
    init: true
    command: "jupyter notebook --allow-root  --ip=0.0.0.0 --no-browser"
    volumes:
      - .:/code
    ports:
      - '8888:8888'
    links:
      - db
volumes:
  dbdata:
