version: '2.3'
services:
  default: &default
    build: .
    #init: true
    user: "${UID}:${GID}"
    #command: "jupyter notebook --allow-root  --ip=0.0.0.0 --no-browser"
    #command: ["bash", "startup.sh"]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "$PWD:/home/user/work"
      - "pgdata:/var/lib/postgresql/10/main/"
    ports:
      - '8888:8888'
  nvidia:
    <<: *default
    runtime: nvidia
volumes:
    pgdata:
