version: '2'
services:
  db:
    image: informaticsmatters/rdkit_cartridge 
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  dbdata:
